# Generated by Django 2.0.13 on 2022-04-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='digital',
            field=models.NullBooleanField(default=False),
        ),
    ]
